//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Engineers
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpu_view
    {
        public int ID { get; set; }
        public Nullable<int> Inventory_Number_CPU { get; set; }
        public string Name { get; set; }
        public string Socket { get; set; }
        public string Clock_Frequency { get; set; }
        public string Name_Room { get; set; }
        public string Description { get; set; }
    }
}
