//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Engineers
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_log
    {
        public int ID { get; set; }
        public Nullable<int> ID_Users { get; set; }
        public string Description { get; set; }
        public string Event { get; set; }
        public string DateTime { get; set; }
    
        public virtual users users { get; set; }
    }
}
