//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Engineers
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_log_view
    {
        public int ID { get; set; }
        public string DateTime { get; set; }
        public string Surname { get; set; }
        public string Event { get; set; }
    }
}
