//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Engineers
{
    using System;
    using System.Collections.Generic;
    
    public partial class pc
    {
        public int ID { get; set; }
        public Nullable<int> Inventory_Number { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_CPU { get; set; }
        public Nullable<int> ID_RAM { get; set; }
        public Nullable<int> ID_Room { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public string Description { get; set; }
    
        public virtual cpu cpu { get; set; }
        public virtual employee employee { get; set; }
        public virtual ram ram { get; set; }
        public virtual room room { get; set; }
    }
}
