//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM_Engineers
{
    using System;
    using System.Collections.Generic;
    
    public partial class pc_viewsklad
    {
        public int ID { get; set; }
        public Nullable<int> Inventory_Number { get; set; }
        public string Name { get; set; }
        public Nullable<int> Inventory_Number_CPU { get; set; }
        public Nullable<int> Inventory_Number_RAM { get; set; }
    }
}
